#!/bin/bash
mv /home/swapnil/backup.tar.gz /home/swapnil/backup.tar.gz_old
tar -czf /home/swapnil/backup.tar.gz /var
find /home/swapnil/backup.tar.gz -mtime -1 -type f -exec {} \;
if [ $? -eq 0 ]
	then
	echo Backup was created.
	echo
	echo Copying Backup on other server
	scp /home/swapnil/backup.tar.gz root@192.168.100.6:/home/shweta/
	if [ $? -eq 0 ]
	then
	echo Backup copied successfully.
	else 
	echo Backup failed
	fi
else 
	echo Dhanyavad bas
fi

