#!/bin/bash
#check direcctories in /home/ and users exist
cd /home
for dir in *
do
	chk=$(grep -c "/home/$dir" /etc/passwd)
	if [ $chk -ge 1 ]
	then
	echo $dir assigned to  user
	else 
	echo $dir not assigned
	fi
done
