#!/bin/bash
echo
echo "please enter day (eg. sun)"
read  day
echo "Please enter a month (eg. May)"
read  month
echo "Please enter a date (eg. 04)"
read tarikh
last | grep -i "$day $month $tarikh" | awk '{print $1}'
echo
