#!/bin/bash
x=`ls -ltr swap* | wc -l`
echo
echo Total $x sec needed to assign the permission	
	
for i in swap*
do
	echo Assigning executable permission to $i
	chmod a+w $i
	echo permission assigned
	sleep 1 
#	echo Removing write and executable permission to $i
#	chmod a-wx $i
#	echo permission removed
#	sleep 1
done
ls -ltr
