#!/bin/bash
echo

for i in swap*
do
    if [ -e "$i" ]; then
        perms=$(stat -c "%A" "$i")
        if [[ $perms == *w* ]]; then
            echo "$i file has already write permission"
        else
            echo Assigning write permission to "$i" file
            chmod a+w "$i"
            if [ $? -eq 0 ]; then
                echo Write permission assigned to "$i" file
            else
                echo Failed to assign write permission to "$i" file
            fi
        fi
    else
        echo "$i file does not exist"
    fi
    sleep 1
done

