#!/bin/bash
# Add a user
echo "enter a username"
read u
echo 

grep -q  $u /etc/passwd
	if [ $? -eq 0 ]
	then
		echo ERROR -- User $u already exist
		echo Please enter another  username
		echo 
		exit 0
	fi
echo  Please provide user description
read d
echo
echo "Do you want to specify user ID  (y/n)?"
read sk
echo
	if [ $sk == y ]
	then
		echo "Please enter UID"
		echo
		read uid
		useradd $u -c "$d" -u $uid
		echo
		echo $u account has been created
	elif [ $sk == n ]
	then
		echo No worries we will assign a UID
		useradd $u -c  "$d"
		echo 
		 echo $u account has been created
	fi
